name: Deploy to Dev
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Coolify Deploy (dev)
      run: |
        curl -fsS -X POST "https://domlab.uz/api/v1/deploy?uuid=u00k4448oo0cs0kgwkck04o0&force=false" -H "Content-Length: 0"
