name: Deploy to Dev
on:
  push:
    branches: [dev]

concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: dev
    steps:
      - name: Trigger Coolify deploy (dev)
        env:
          COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
          COOLIFY_WEBHOOK_URL_DEV: https://coolify.domlab.uz/api/v1/deploy?tag=prod-deploy
        run: |
          curl --fail-with-body -sS \
            --retry 3 --retry-delay 5 --max-time 60 \
            -X POST "$COOLIFY_WEBHOOK_URL_DEV" \
            -H "Authorization: Bearer $COOLIFY_API_TOKEN" \
            -H "Content-Type: application/json"
