name: Deploy to Dev
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
    - name: Trigger Coolify Deploy (dev)
      env:
        COOLIFY_WEBHOOK_URL: "https://coolify.domlab.uz/api/v1/deploy?uuid=u00k4448oo0cs0kgwkck04o0&force=false"
        COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
      run: |
        curl -fsS -X POST "$COOLIFY_WEBHOOK_URL" \
          -H "Authorization: Bearer $COOLIFY_API_TOKEN" \
          -H "Content-Length: 0" \
          --retry 5 --retry-connrefused --retry-delay 2
