name: Deploy to Dev
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: dev
    steps:
      - name: Trigger Coolify deploy by tag (dev)
        env:
          COOLIFY_API_TOKEN: ${{ secrets.COOLIFY_API_TOKEN }}
          COOLIFY_WEBHOOK_URL_DEV: ${{ secrets.COOLIFY_WEBHOOK_URL_DEV }}
        run: |
          curl -fsS "$COOLIFY_WEBHOOK_URL_DEV" \
            -H "Authorization: Bearer $COOLIFY_API_TOKEN"
