name: Deploy to Dev
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev # ? ?????: ????? ??????? ?? env "dev"
    steps:
    - name: Trigger Coolify Deploy (dev)
      env:
        COOLIFY_WEBHOOK_URL: ${{ secrets.COOLIFY_WEBHOOK_URL }} # ? ??? ??? ? ????? env
      run: |
        echo "POST $COOLIFY_WEBHOOK_URL"
        curl -fsS -X POST "$COOLIFY_WEBHOOK_URL" -H "Content-Length: 0"
