name: Release Please

on:
  push:
    branches: [main] # ?????? ?? main
  workflow_dispatch: # ????? ????????? ??????

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
